In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import ensemble
from sklearn import linear_model
import seaborn as sns
import matplotlib.pyplot as plt
from functions import *
import warnings
import random
from pandas.core.common import SettingWithCopyWarning
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

In [46]:
baskets, coupons, prediction_index = get_3_files()

In [47]:
n_customers = 20
customers = range(2000)#random.sample(range(2000),n_customers)
baskets = baskets[baskets['customer'].isin(customers)]
coupons = coupons[coupons['customer'].isin(customers)]
base = create_base(weeks=range(91),customers=customers)

In [48]:
base = add_basket_info(base, baskets)

In [49]:
base = add_categories(base)

In [50]:
base = add_frequencies(base, baskets) #Will generate frequencies based on available basket info

In [51]:
base = add_rolling_frequencies(base)

In [ ]:
base = add_weeks_ago(base)

In [ ]:
base = base.drop(['price','basket'],axis=1)

In [ ]:
base

,week,customer,product,isBought,category,p_prod,p_cat,roll_prod_5,roll_prod_10,roll_prod_30,weeks_ago
0,0,1218,0,False,0,0.0,0.211111,0.0,0.0,0.0,90.0
1,0,1218,1,False,0,0.0,0.211111,0.0,0.0,0.0,90.0
2,0,1218,2,False,0,0.0,0.211111,0.0,0.0,0.0,90.0
3,0,1218,3,False,0,0.0,0.211111,0.0,0.0,0.0,90.0
4,0,1218,4,False,0,0.0,0.211111,0.0,0.0,0.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...
454995,90,998,245,False,24,0.0,0.633333,0.0,0.0,0.0,90.0
454996,90,998,246,False,24,0.0,0.633333,0.0,0.0,0.0,90.0
454997,90,998,247,False,24,0.0,0.633333,0.0,0.0,0.0,90.0
454998,90,998,248,False,24,0.0,0.633333,0.0,0.0,0.0,90.0
454999,90,998,249,False,24,0.6,0.633333,0.0,0.0,0.0,90.0

In [ ]:
train = base[base['week']<90]
predict = base[base['week']==90]

In [ ]:
x_train = train.drop('isBought',axis=1)
y_train = train['isBought']

In [ ]:
x_predict = predict.drop('isBought',axis=1)

In [ ]:
x_predict

,week,customer,product,category,p_prod,p_cat,roll_prod_5,roll_prod_10,roll_prod_30,weeks_ago
450000,90,1218,0,0,0.0,0.211111,0.0,0.0,0.0,90.0
450001,90,1218,1,0,0.0,0.211111,0.0,0.0,0.0,90.0
450002,90,1218,2,0,0.0,0.211111,0.0,0.0,0.0,90.0
450003,90,1218,3,0,0.0,0.211111,0.0,0.0,0.0,90.0
450004,90,1218,4,0,0.0,0.211111,0.0,0.0,0.0,90.0
...,...,...,...,...,...,...,...,...,...,...
454995,90,998,245,24,0.0,0.633333,0.0,0.0,0.0,90.0
454996,90,998,246,24,0.0,0.633333,0.0,0.0,0.0,90.0
454997,90,998,247,24,0.0,0.633333,0.0,0.0,0.0,90.0
454998,90,998,248,24,0.0,0.633333,0.0,0.0,0.0,90.0
454999,90,998,249,24,0.6,0.633333,0.0,0.0,0.0,90.0

In [ ]:
models = [
    ensemble.RandomForestClassifier(), #2.6%
    ensemble.GradientBoostingClassifier(), #1.9%
    ensemble.HistGradientBoostingClassifier() #2.4%
]

In [ ]:
model_list = []

for model in models:
    print(model)
    model.fit(X = x_train, y = y_train)
    model_list.append(model)

RandomForestClassifier()
GradientBoostingClassifier()
HistGradientBoostingClassifier()

In [ ]:
np.matrix(predictions_list).mean(axis=0)

matrix([[0.99999908, 0.99999908, 0.99999908, ..., 0.99999908, 0.99999908,
         0.99999908]])

In [ ]:
predictions = model.predict_proba(x_predict)[:,0]
predictions_list.append(predictions)

In [ ]:
prediction_index['predictions'] =

        week customer product
0         90        0       0
1         90        0       1
2         90        0       2
3         90        0       3
4         90        0       4
...      ...      ...     ...
499995    90     1999     245
499996    90     1999     246
499997    90     1999     247
499998    90     1999     248
499999    90     1999     249

[500000 rows x 3 columns]